description: Please fill user and password fields in the following. You may customize sections / extensions if needed.
user:
password: 
sections:
    - product_download
    - installation_guides
    - user_manuals
    - plugins
    - plugins_modules
extensions:
    - .pdf
    - .fpi
    - .img
    - .iso
url: https://updates.forescout.com/support/index.php?url=counteract
